owner: firstquadrant-ai
repo: status
sites:
  - name: FirstQuadrant web app
    url: https://firstquadrant.ai
  - name: FirstQuadrant API
    url: https://firstquadrant.ai/api/health
status-website:
  cname: status.firstquadrant.ai
  logoUrl: https://avatars.githubusercontent.com/u/122780401?s=88&v=4
  name: FirstQuadrant
  navbar:
    - title: FirstQuadrant
      href: https://firstquadrant.ai
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
